name: Build EDK2 and package OVMF

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-edk2:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout this repo (optional)
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential uuid-dev iasl git gcc-10 g++-10 nasm python3
        
    - name: Set up GCC
      run: |
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 100
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
        
    - name: Clone EDK2 repository
      run: |
        git clone https://github.com/tianocore/edk2.git
        cd edk2
        git submodule update --init
        
    - name: Build EDK2 BaseTools
      run: |
        cd edk2
        make -C BaseTools
        
    - name: Setup EDK2 environment
      run: |
        cd edk2
        export EDK_TOOLS_PATH=$PWD/BaseTools
        . edksetup.sh
        
    - name: Build OVMF
      run: |
        cd edk2
        build -a X64 -p OvmfPkg/OvmfPkgX64.dsc -t GCC5 -b RELEASE
        
    - name: Upload OVMF.fd as artifact
      uses: actions/upload-artifact@v4
      with:
        name: OVMF.fd
        path: edk2/Build/OvmfX64/RELEASE_GCC5/FV/OVMF.fd
